package pe.gob.mpfn.cfms.mesadeturno.enums;

import lombok.Getter;

@Getter
public enum ObjectosOracle {
    SISMPA("SISMPA"),
    MPPK_DENUNCIA_TURNO("MPPK_DENUNCIA_TURNO"),
    PK_DENUNCIA_PARTES("MPPK_DENUNCIA_PARTES_TURNO"),

    MPPK_DELITOS_PARTES_TURNO("MPPK_DELITOS_PARTES_TURNO"),
    MPPK_DOCUMENTO_CASO_TURNO("MPPK_DOCUMENTO_CASO_TURNO"),
    MPPK_REGISTRA_DENUNCIA_TURNO("MPPK_REGISTRA_DENUNCIA_TURNO"),
    MPSP_LISTAR_DENUNCIAS_REGISTRADAS("MPSP_LISTAR_DENUNCIAS_REGISTRADAS"),
    MPSP_INSERTAR_DATOS_GENERALES("MPSP_INSERTAR_DATOS_GENERALES"),
    SP_LISTAR_TIPOS_PARTE_SUJETO("MPSP_LISTAR_TIPOS_PARTE_SUJETO"),
    SP_LISTAR_PERSONA_TIPO_PARTE_SUJETO("MPSP_LISTAR_PERSONA_TIPO_PARTE_SUJETO"),
    MPSP_LISTAR_DELITOS("MPSP_LISTAR_DELITOS"),
    MPSP_LISTAR_PERSONAS_NATURALES("MPSP_LISTAR_PERSONAS_NATURALES"),
    MPSP_LISTAR_PERSONAS_JURIDICAS("MPSP_LISTAR_PERSONAS_JURIDICAS"),
    MPSP_IMPUTADOS_RENADESPPLE("MPSP_IMPUTADOS_RENADESPPLE"),
    MPSP_VALIDAR_SI_MESA_ESTA_DE_TURNO("MPSP_VALIDAR_SI_MESA_ESTA_DE_TURNO"),
    MPPK_CASO_TURNO("MPPK_CASO_TURNO"),
    SP_REGISTRAR_HECHOS_CASO("REGISTRAR_HECHOS_CASO"),
    MPSP_BUSCAR_DELITOS("MPSP_BUSCAR_DELITOS"),
    MPSP_LISTAR_TIPOS_GRADO_DELITO("MPSP_LISTAR_TIPOS_GRADO_DELITO"),
    MPSP_REGISTRAR_DELITO("MPSP_REGISTRAR_DELITO"),
    MPSP_REGISTRAR_DETENIDO_DELITO("MPSP_REGISTRAR_DETENIDO_DELITO"),
    MPSP_VALIDAR_DUPLICIDAD("MPSP_VALIDAR_DUPLICIDAD"),
    MPSP_LISTAR_ACTAS_REGISTRADAS("MPSP_LISTAR_ACTAS_REGISTRADAS"),
    MPSP_REGISTRAR_MOVIMIENTO("MPSP_REGISTRAR_MOVIMIENTO"),
    MPSP_REGISTRAR_DENUNCIA_TURNO("MPSP_REGISTRAR_DENUNCIA_TURNO"),
    CR_HECHOS("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.CR_HECHOS"),
    T_HECHO("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.T_HECHO"),
    CR_PARTES("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.CR_PARTES"),
    T_PARTE("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.T_PARTE"),
    CR_DELITOS("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.CR_DELITOS"),
    T_DELITO("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.T_DELITO"),
    CR_DIRECCION("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.CR_DIRECCION"),
    T_DIRECCION("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.T_DIRECCION"),
    CR_CONTACTO("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.CR_CONTACTO"),
    T_CONTACTO("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.T_CONTACTO"),
    CR_DATOS_GENERALES("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.CR_DATOS_GENERALES"),
    T_DATOS_GENERALES("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.T_DATOS_GENERALES"),
    CR_DETENIDOS("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.CR_DETENIDOS"),
    T_DETENIDO("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.T_DETENIDO"),
    CR_DELITOS_ASOCIADOS("SISMPA.MPPK_REGISTRA_DENUNCIA_TURNO.CR_DELITOS_ASOCIADOS"),
    SP_LISTAR_PARTES_INVOLUCRADAS_NATURAL("MPSP_LISTAR_PARTE_INVOLUCRADA_NATURAL"),
    MPSP_RECUPERAR_DATOS_GENERALES("MPSP_RECUPERAR_DATOS_GENERALES"),
    SP_LISTAR_HECHOS_DENUNCIA("MPSP_LISTAR_HECHOS_DENUNCIA"),
    SP_LISTAR_PARTE_INVOLUCRADA_JURIDICA("MPSP_LISTAR_PARTE_INVOLUCRADA_JURIDICA"),
    SP_LISTAR_DIRECCIONES_SUJETO("MPSP_LISTAR_DIRECCIONES_SUJETO"),
    SP_LISTAR_SUJETO_CONTACTO("MPSP_LISTAR_SUJETO_CONTACTO"),
    SP_LISTAR_DELITOS_DENUNCIA("MPSP_LISTAR_DELITOS_POR_DENUNCIA"),
    SP_LISTAR_DELITOS_SUJETO("MPSP_LISTAR_DELITOS_SUJETO"),
    MPSP_OBTENER_DATOS_GENERALES_DENUNCIA_OFICIO("MPSP_OBTENER_DATOS_GENERALES_DENUNCIA_OFICIO"),
    MPSP_LISTAR_OFICINAS_RENADESPPLE("MPSP_LISTAR_OFICINAS_RENADESPPLE"),
    MPSP_LISTAR_MOTIVOS_DETENCION("MPSP_LISTAR_MOTIVOS_DETENCION"),
    MPSP_LISTAR_SITUACIONES_JURIDICAS("MPSP_LISTAR_SITUACIONES_JURIDICAS"),
    MPSP_LISTAR_DIRECCIONES_INFO("MPSP_LISTAR_DIRECCIONES_INFO"),
    MPSP_REGISTRAR_DIRECCION_INFO("MPSP_REGISTRAR_DIRECCION_INFO"),
    MPSP_ACTUALIZAR_DIRECCION_INFO("MPSP_ACTUALIZAR_DIRECCION_INFO"),
    MPSP_ELIMINAR_DIRECCION_INFO("MPSP_ELIMINAR_DIRECCION_INFO"),
    MPSP_REGISTRAR_ACTUALIZAR_FICHA_RENADESPPLE("MPSP_REGISTRAR_ACTUALIZAR_FICHA_RENADESPPLE"),
    MPSP_FOLIAR_DOCUMENTOS_REGISTRADOS("MPSP_FOLIAR_DOCUMENTOS_REGISTRADOS"),
    MPSP_OBTENER_FICHA_RENADESPPLE("MPSP_OBTENER_FICHA_RENADESPPLE"),
    MPSP_OBTENER_MOMENTO_DETENCION("MPSP_OBTENER_MOMENTO_DETENCION"),
    MPSP_OBTENER_INVESTIGACION_POLICIAL("MPSP_OBTENER_INVESTIGACION_POLICIAL"),
    MPSP_CONSULTAR_PERSONA("MPSP_CONSULTAR_PERSONA"),
    MPSP_REGISTRAR_MOVIMIENTO_INGRESO_DENUNCIA("MPSP_REGISTRAR_MOVIMIENTO_INGRESO_DENUNCIA"),
    MPSP_IDENTIFICAR_DENUNCIA_DUPLICADA("MPSP_IDENTIFICAR_DENUNCIA_DUPLICADA"),
    MPFN_OBTENER_ESPECIALIDAD("MPFN_OBTENER_ESPECIALIDAD");

    private final String value;

    ObjectosOracle(String value) {
        this.value = value;
    }
}
